config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end
  get "pages/about", to: "pages#about"
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  obfuscate_id
	acts_as_votable
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def has_expired?
    if (self.expiration <=> Date.today) == (-1) then true else false end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :name
	  devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.post_id = @post.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index]
  before_action :require_permission, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @comments = Comment.where(post_id: @post)
    @random_post = Post.where.not(id: @post).order("RANDOM()").first

  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_from current_user
    redirect_to :back
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def require_permission
    if current_user != Post.find(params[:id]).user
      redirect_to root_path
    end
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image, :expiration, :minimum_price, :minimum_order)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :content, label: "Reply to thread"
	= f.button :submit, class: "button"

app/views/layouts/_footer.html.erb
<script> (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-66639573-1', 'herokuapp.com'); ga('send', 'pageview'); 
</script>

app/views/layouts/_footer.html.haml
<script> (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-66639573-1', 'herokuapp.com'); ga('send', 'pageview'); 
</script>

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Apparel Chair
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	%link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}
	%link{:rel => "stylesheet", :href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"}
	= csrf_meta_tags
%body
	%header
		.wrapper.clearfix
			#logo= link_to "Apparel Chair", root_path
			%nav
				- if user_signed_in?
					= link_to "Add New Idea", new_post_path, class: "button"
					= link_to current_user.name, edit_user_registration_path
					= link_to "About", pages_about_path
					= link_to "Sign Out", destroy_user_session_path, method: :delete
				- else
					= link_to "Sign in", new_user_session_path
					= link_to "Sign Up", new_user_registration_path, class: "button"
	%p.notice= notice
	%p.alert= alert
	.wrapper
		= yield

= render 'layouts/footer'

app/views/pages/about.html.haml
- if user_signed_in?	
	%h2 Backing an Idea
	%h3
		1. See what's listed, and understand that orders are considered only if they hit their minimum number of units at the price quoted.
		%br/
	%h3
		2. So if there's something you like, click the item and click that "you're buying it".
	%h3
		3. Once you commit to buying it once the expiration date hits, you will be charged via Venmo (so use your Venmo ID as your name).
	%h3
		4. You are liable to paying it as otherwise you ___ your brothers.
	%h3 
		5. Please pay promptly when you're charged and feel free to post snarky comments everywhere. 
	%h2 Adding an Idea
	%h3 1. Think about the minimum number of people you would need to place an order.
	%h3 2. Figure out the price for that minimum number of people.
	%h3 3. Download and upload a picture and attach a link.
	%h3 3a. If you are planning something like paintball, attach a link to the place.
	%h3 3b. If you are designing apparel, attach a link to the Customink order.
	%h3 4. Set a date where at midnight EST you will not count more people in.
	%h3 4a. All people who say they are buying in are liable to paying or they will be fined.
	%h3 5. Add a description using your wit.
	%h3 6. Finally once the time is hit, see who opted into buying your product and charge them all via either Venmo or cash.
	%br/
	%span P.S. I would have integrated Venmo but their compliance department doesn't really like me and won't give me API keys. If you want to help with the code it's on my <a href="https://github.com/udaysinghcode/apparelchair">Github</a>. This is a total work in progress and was made over two days so it's very scrappy.
	%br/
	%br/
	%span Enjoy!

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
	= f.input :image, required: :true
	= f.input :title, required: :true
	= f.input :link, required: :true
	= f.input :minimum_order, label: 'Minimum number you want to order', required: :true
	= f.input :minimum_price, label: 'Price per unit of the minimum order rounded up $', required: :true
	= f.input :expiration, as: :date, required: :true
	= f.input :description, required: :true

	= f.button :submit

app/views/posts/_form_edit.html.haml
= simple_form_for @post do |f|
	= f.input :image
	= f.input :title
	= f.input :link
	= f.input :minimum_order, label: 'Minimum number you want to order'
	= f.input :minimum_price, label: 'Price per unit of the minimum order rounded up'
	= f.input :expiration, as: :date
	= f.input :description
	= f.button :submit

app/views/posts/edit.html.haml
%h1 Edit Inspiration

= render 'form_edit'

app/views/posts/index.html.haml
- if user_signed_in?
	%p#intro
		Hello
		= current_user.name
		%br/
		%span
			Is there something you're interested in today?
			%br/
		%span
			Click 'About' to understand the rules and how this works!
- else
	%p#intro
		List your apparel ideas, event ideas, and more!
		%br/
		%span
			See who wants to get involved so we can book big apparel orders and cool events with more transparency!

#posts
	- @posts.each do |post|
		- if !post.has_expired?
			.post
				.post_image
					= link_to (image_tag post.image.url(:small)), post
				.post_content
					.title
						%h2= link_to post.title, post
					.title
						%h2
							$
							= post.minimum_price
							per person
						%h2
							Minimum
							= pluralize(post.minimum_order, "order")
							required
					.data.clearfix
						%p.username
							Shared by
							= post.user.name
						%p.buttons
							%span
								%i.fa.fa-comments-o
								= post.comments.count
							%span
								%i.fa.fa-thumbs-o-up
								= post.get_likes.size
.clearfix
%p#intro
	Past Posts
	%br/
	%span
		See what's happened in the past!
	
#posts
	- @posts.each do |post|
		- if post.has_expired?
			.post
				.post_image
					= link_to (image_tag post.image.url(:small)), post
				.post_content
					.title
						%h2= link_to post.title, post
					.title
						%h2
							$
							= post.minimum_price
							per person
						%h2
							Minimum
							= pluralize(post.minimum_order, "order")
							required
					.data.clearfix
						%p.username
							Shared by
							= post.user.name
						%p.buttons
							%span
								%i.fa.fa-comments-o
								= post.comments.count
							%span
								%i.fa.fa-thumbs-o-up
								= post.get_likes.size

.clearfix
- if user_signed_in?
	%p#intro
		%span
			Made on no sleep by the <a href="http://uday.io">Apparel Chair</a>.

app/views/posts/new.html.haml
%h1 Add a New Idea
%h3 1. Think about the minimum number of people you would need to place an order.
%h3 2. Figure out the price for that minimum number of people.
%h3 3. Download and upload a picture and attach a link.
%h3 3a. If you are planning something like paintball, attach a link to the place.
%h3 3b. If you are designing apparel, attach a link to the Customink order.
%h3 4. Set a date where at midnight EST you will not count more people in.
%h3 4a. All people who say they are buying in are liable to paying or they will be fined.
%h3 5. Add a description using your wit.

= render 'form'

app/views/posts/show.html.haml
#post_show
	%h1= @post.title 

	- if @post.has_expired?
		%p.username
			Shared by
			= @post.user.name
			about
			= time_ago_in_words(@post.created_at)
			ago. Post expired
			= @post.expiration
	- else
		%p.username
			Shared by
			= @post.user.name
			about
			= time_ago_in_words(@post.created_at)
			ago. Post expires
			= @post.expiration

	.clearfix
		.post_image_description
			= image_tag @post.image.url(:medium)
			%p.username
				$ 
				= @post.minimum_price
				| Minimum
				= pluralize(@post.minimum_order, "order")
				required
			.description= simple_format(@post.description)

		.post_data
			= link_to "Visit Link", @post.link, class: "button"
			- if @post.has_expired?
				= link_to "https://www.youtube.com/tv#/watch?v=s8LIRtPnuA8&feature=youtu.be&t=1m4s", class: "data" do
					%i.fa.fa-minus-circle
					\... Too Late (To Buy)
			- else
				= link_to like_post_path(@post), method: :get, class: "data" do
					%i.fa.fa-thumbs-o-up
					= pluralize(@post.get_upvotes.size, "buyer")
				= link_to dislike_post_path(@post), method: :get, class: "data" do
					%i.fa.fa-thumbs-o-down
					= pluralize(@post.get_downvotes.size, "non-buyer")
			%p.data
				%i.fa.fa-comments-o
				= pluralize(@post.comments.count, "Comment")
			- if @post.user == current_user 
				= link_to "Edit", edit_post_path(@post), class: "data"
				= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "data"
			%p.comment_count
				= pluralize(@post.get_upvotes.size, "person") 
				buying
			- @post.votes_for.up.by_type(User).voters.each do |voter|
				.comment
					%p.username= voter.name

#comments
	%h2.comment_count= pluralize(@post.comments.count, "comment")
	- @comments.each do |comment|
		.comment
			%p.username= comment.user.name
			%p.content= comment.content

	= render "comments/form"